# Default colors
[colors.primary]
background = '0x172237'
foreground = '0xd1d5da'

[colors.cursor]
text = '0x000000'
cursor = '0xffffff'

# Normal colors
[colors.normal]
black = '0x586069'
red = '0xea4a5a'
green = '0x34d058'
yellow = '0xffea7f'
blue = '0x2188ff'
magenta = '0xb392f0'
cyan = '0x39c5cf'
white = '0xd1d5da'

# Bright colors
[colors.bright]
black = '0x959da5'
red = '0xf97583'
green = '0x85e89d'
yellow = '0xffea7f'
blue = '0x79b8ff'
magenta = '0xb392f0'
cyan = '0x56d4dd'
white = '0xfafbfc'
